### ISSUE TITLE
关闭消息提醒以及重载插件报错。

### ISSUE THREAD

**Issue by juzhijian** [Tollainmear/KaroglanSignEditor#7]
海绵端spongeforge-1.12.2-2705-7.1.0-BETA-3206.jar

关闭消息提醒找不到命令！

`[23:46:25] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Input command on was not a valid subcommand!
on
^
[23:46:25] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Usage: /kse trust|trustlist|set|swap|clear|redo|paste|clipboard|version|undo|reload|untrust|copy
[23:47:04] [Server thread/INFO] [rankup]: Times updated for 2 player(s)
`

重载插件出错。
`[23:48:02] [Server thread/INFO] [nucleus]: Server 执行指令: /kse reload
[23:48:02] [Server thread/INFO] [karoglansigneditor]: 语言文件已加载。
[23:48:02] [Server thread/INFO] [karoglansigneditor]: 语言文件已加载。
[23:48:02] [Server thread/INFO] [karoglansigneditor]: 语言文件已经是最新版本。
[23:48:02] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Error occurred while executing command: A plugin may not register multiple commands for the same alias ('kse')!
[23:48:02] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'kse reload' for source DedicatedServer: A plugin may not register multiple commands for the same alias ('kse')!
java.lang.IllegalArgumentException: A plugin may not register multiple commands for the same alias ('kse')!
        at org.spongepowered.common.command.SpongeCommandManager.register(SpongeCommandManager.java:157) ~[SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.command.SpongeCommandManager.register(SpongeCommandManager.java:126) ~[SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.command.SpongeCommandManager.register(SpongeCommandManager.java:121) ~[SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.karoglan.tollainmear.signeditor.KSECommandManager.init(KSECommandManager.java:138) ~[KSECommandManager.class:?]
        at org.karoglan.tollainmear.signeditor.KSECommandManager.<init>(KSECommandManager.java:133) ~[KSECommandManager.class:?]
        at org.karoglan.tollainmear.signeditor.commandexecutor.ReloadExecutor.execute(ReloadExecutor.java:28) ~[ReloadExecutor.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3206]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[23:48:04] [Server thread/INFO] [rankup]: Times updated for 2 player(s)
`

**Comment by juzhijian** [comment]
![qq 20180629235803](https://user-images.githubusercontent.com/14793250/42102657-2c3d8084-7bf9-11e8-8899-20f9a31b3b77.png)
这个可以不可以给整个语言文件。强迫症受不了啊。
